### ISSUE TITLE
How does your QVLM model perform?

### ISSUE THREAD

**Issue by bagh2178** [ChangyuanWang17/QVLM#2]

**Comment by Yiman-GO** [comment]
same question. I did't see any code about quantization.

**Comment by ChangyuanWang17** [comment]
Thank you for your patience. We are happy to share that we recently released our paper on [arxiv](https://arxiv.org/abs/2410.08119)! For information on model performance and hyperparameter settings, you can refer to the description and tables in the experimental section. 

Additionally, the code for the quantization part is provided in the `custom_bitsandbytes/bitsandbytes/quantization_utils/` folder, which describes efficient memory reduction, and can be used as a reference!

**Comment by bagh2178** [comment]
Thanks for your nice quantization model! The model performance is excellent.
