### ISSUE TITLE
关于bitsandbytes库的使用问题

### ISSUE THREAD

**Issue by half-lang** [ChangyuanWang17/QVLM#4]
按照readme中的方式安装该库后出现如下报错：
CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
我的环境：GPU：3090 ubuntu22.04 CUDA：11.8

**Comment by half-lang** [comment]
我找到了该问题的解决方法https://github.com/bitsandbytes-foundation/bitsandbytes/issues/748#issuecomment-1718288302，在尝试修改环境变量后没有作用，之后进行如下尝试：修改/envs/QVLM/lib/python3.10/site-packages/bitsandbytes-0.41.1-py3.10.egg/bitsandbytes/cuda_setup/main.py文件中的CUDA_RUNTIME_LIBS: list = ["libcudart.so", 'libcudart.so.11.0', 'libcudart.so.11.8.89']，具体数值为你的cuda文件夹中lib64对应文件。最后export BNB_CUDA_VERSION=118

**Comment by ChangyuanWang17** [comment]
很高兴您分享了您的解决方案:)
