### ISSUE TITLE
Question about bitsandbytes

### ISSUE THREAD

**Issue by Leon1207** [ChangyuanWang17/QVLM#5]
Thanks for your great work!
I would like to ask about your modification in bitsandbytes library since we don't have cuda11 driver, so we are trying to transfer it into the new version of bitsandbytes to run it on cuda12. Thanks!

**Comment by ChangyuanWang17** [comment]
Thanks for your attention to our work. The main modification​ focus on ​custom_bitsandbytes/bitsandbytes/quantization_utils and custom_bitsandbytes/bitsandbytes/nn/modules.py​ ​as reference​.

**Comment by Leon1207** [comment]
Thanks for your reply!




东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ChangyuanWang17/QVLM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月2日(星期一) 中午12:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ChangyuanWang17/QVLM] Question about bitsandbytes (Issue #5)





 
Thanks for your attention to our work. The main modification​ focus on ​custom_bitsandbytes/bitsandbytes/quantization_utils and custom_bitsandbytes/bitsandbytes/nn/modules.py​ ​as reference​.

**Comment by Leon1207** [comment]
Thanks for your reply, I would like to ask if there are any modifications in the source code of LLaVA? I need to use bitsandbytes==0.44.2.dev0 for compiling and it seems incompatible with llava 1.0.1.

**Comment by ChangyuanWang17** [comment]
No, we jest dirrectly use the source code of LLaVA and deploy bitsandbytes==0.41.0 in pyproject.toml



-----原始邮件-----
发件人:"Yongdong Luo" ***@***.***>
发送时间:2024-12-02 17:30:58 (星期一)
收件人: ChangyuanWang17/QVLM ***@***.***>
抄送: "Changyuan Wang" ***@***.***>, Comment ***@***.***>
主题: Re: [ChangyuanWang17/QVLM] Question about bitsandbytes (Issue #5)






Thanks for your reply, I would like to ask if there are any modifications in the source code of LLaVA? I need to use bitsandbytes==0.44.2.dev0 for compiling and it seems incompatible with llava 1.0.1.

**Comment by Leon1207** [comment]
Thanks for your kindly sharing!

**Comment by Wotoosh** [comment]
您好，看到这条issue想请问custom_bitsandbytes是只能在cuda11X上运行吗，我服务器上的cuda driver的版本是12.2，在尝试各种办法后仍遇到了CUDA Setup failed despite GPU being available的问题，不知道是不是和cuda版本有关，谢谢您 @ChangyuanWang17
